"""initial migration

Revision ID: 423a323eabcc
Revises: 9e9fb3f0bd4c
Create Date: 2017-05-16 23:14:18.100576

"""

# revision identifiers, used by Alembic.
revision = '423a323eabcc'
down_revision = '9e9fb3f0bd4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
