"""initial migration

Revision ID: 6960a2689a2a
Revises: bfcca79c4902
Create Date: 2017-05-30 15:45:17.930387

"""

# revision identifiers, used by Alembic.
revision = '6960a2689a2a'
down_revision = 'bfcca79c4902'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
