"""initial migration

Revision ID: 72c1c2d6dc06
Revises: 9a8d07e27b1c
Create Date: 2017-05-18 22:25:44.864584

"""

# revision identifiers, used by Alembic.
revision = '72c1c2d6dc06'
down_revision = '9a8d07e27b1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
