"""initial migration

Revision ID: 779e67a86e1f
Revises: 72c1c2d6dc06
Create Date: 2017-05-22 19:53:12.089860

"""

# revision identifiers, used by Alembic.
revision = '779e67a86e1f'
down_revision = '72c1c2d6dc06'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
