"""initial migration

Revision ID: 9e9fb3f0bd4c
Revises: 918d18cfc0f8
Create Date: 2017-05-16 21:20:06.997715

"""

# revision identifiers, used by Alembic.
revision = '9e9fb3f0bd4c'
down_revision = '918d18cfc0f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
