"""initial migration

Revision ID: f6e2e617d9a0
Revises: 456a945560f6
Create Date: 2017-05-12 20:09:22.755405

"""

# revision identifiers, used by Alembic.
revision = 'f6e2e617d9a0'
down_revision = '456a945560f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
